# Generated by Django 3.0.2 on 2021-01-01 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('dob', models.DateField()),
                ('mobileNo', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
