# Generated by Django 3.0.2 on 2021-01-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nursery', '0002_nursery_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('nursery', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Nursery.Nursery')),
                ('plant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Nursery.Plant')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Nursery.user')),
            ],
        ),
    ]
