# Generated by Django 3.0.2 on 2021-01-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nursery', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='is_nursery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nursery',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_nursery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
